# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Plug In Colorado
email: plugincolorado@gmail.com
description: >
  Plug In Colorado brings you interviews with interesting people that make up
  our community.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://plugincolorado.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: plugincolorado
timezone: America/Denver
permalink: "/:year/:month/:day/:title/"

bootstrap:
  assets: true
font-awesome:
  assets: true
assets:
  features:
    automatic_img_size: 2
    automatic_img_alt: false

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true
gems:
  - jekyll-feed
  - jekyll-bootstrap-sass
  - jekyll-font-awesome-sass
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
